# Generated by Django 5.1.3 on 2026-01-09 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfirmation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emailconfirmation',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
